const languageColors = [
  { name: 'JavaScript', color: '#f1e05a' },
  { name: 'TypeScript', color: '#3178c6' },
  { name: 'Python', color: '#3572A5' },
  { name: 'Java', color: '#b07219' },
  { name: 'C++', color: '#f34b7d' },
  { name: 'Ruby', color: '#701516' },
  { name: 'PHP', color: '#4F5D95' },
  { name: 'C#', color: '#178600' },
  { name: 'Go', color: '#00ADD8' },
  { name: 'Swift', color: '#ffac45' },
  { name: 'Kotlin', color: '#A97BFF' },
  { name: 'Rust', color: '#dea584' },
  { name: 'Dart', color: '#00B4AB' },
  { name: 'Scala', color: '#c22d40' },
  { name: 'Shell', color: '#89e051' },
  { name: 'ObjectiveC', color: '#438eff' },
  { name: 'Perl', color: '#0298c3' },
  { name: 'Haskell', color: '#5e5086' },
  { name: 'Lua', color: '#000080' },
  { name: 'R', color: '#198CE7' },
  { name: 'Elixir', color: '#6e4a7e' },
  { name: 'Clojure', color: '#db5855' },
  { name: 'Erlang', color: '#B83998' },
  { name: 'HTML', color: '#e34c26' },
  { name: 'CSS', color: '#563d7c' },
  { name: 'Vue', color: '#41b883' },
  { name: 'Svelte', color: '#ff3e00' },
  { name: 'React', color: '#61dafb' },
  { name: 'Angular', color: '#dd1b16' },
  { name: 'Sass', color: '#a53b70' },
  { name: 'Less', color: '#1d365d' },
  { name: 'Stylus', color: '#ff6347' },
  { name: 'CoffeeScript', color: '#244776' },
  { name: 'TeX', color: '#3D6117' },
  { name: 'VimScript', color: '#199f4b' },
  { name: 'EmacsLisp', color: '#c065db' },
  { name: 'Makefile', color: '#427819' },
  { name: 'Dockerfile', color: '#384d54' },
  { name: 'PowerShell', color: '#012456' },
  { name: 'MATLAB', color: '#e16737' },
  { name: 'Groovy', color: '#e69f56' },
  { name: 'Puppet', color: '#302B6D' },
  { name: 'Julia', color: '#a270ba' },
  { name: 'F#', color: '#b845fc' },
  { name: 'OCaml', color: '#3be133' },
  { name: 'CommonLisp', color: '#3fb68b' },
  { name: 'D', color: '#ba595e' },
  { name: 'Scheme', color: '#1e4aec' },
  { name: 'Racket', color: '#22228f' },
  { name: 'Ada', color: '#02f88c' },
  { name: 'Fortran', color: '#4d41b1' },
  { name: 'Assembly', color: '#6E4C13' },
  { name: 'COBOL', color: '#9afff0' },
  { name: 'Crystal', color: '#000100' },
  { name: 'Nim', color: '#ffc200' },
  { name: 'Pascal', color: '#E3F171' },
  { name: 'VHDL', color: '#adb2cb' },
  { name: 'Verilog', color: '#b2b7f8' },
  { name: 'Prolog', color: '#74283c' },
  { name: 'Haxe', color: '#df7900' },
  { name: 'PureScript', color: '#1D222D' },
  { name: 'Forth', color: '#341708' },
  { name: 'OpenSCAD', color: '#e5cd45' },
  { name: 'GLSL', color: '#5686a5' },
  { name: 'QML', color: '#44a51c' },
  { name: 'Solidity', color: '#AA6746' },
  { name: 'Tcl', color: '#e4cc98' },
  { name: 'Eiffel', color: '#946d57' },
  { name: 'Smalltalk', color: '#596706' },
  { name: 'Vala', color: '#fbe5cd' },
  { name: 'Nix', color: '#7e7eff' },
  { name: 'Zig', color: '#ec915c' },
  { name: 'Pony', color: '#cfa76e' },
  { name: 'Idris', color: '#b30000' },
  { name: 'Agda', color: '#315665' },
  { name: 'Coq', color: '#d0b68c' },
  { name: 'Lean', color: '#e5b62f' },
  { name: 'Isabelle', color: '#fe0a0a' },
  { name: 'Mercury', color: '#ff2b2b' },
  { name: 'Turing', color: '#cf142b' },
  { name: 'ActionScript', color: '#882B0F' },
  { name: 'ASP', color: '#6a40fd' },
  { name: 'ColdFusion', color: '#ed2cd6' },
  { name: 'Euphoria', color: '#ff7900' },
  { name: 'Harbour', color: '#0e60e3' },
  { name: 'J', color: '#9EEDFF' },
  { name: 'KRL', color: '#28431f' },
  { name: 'Logtalk', color: '#295b9a' },
  { name: 'MLIR', color: '#5EC8DB' },
  { name: 'Modula2', color: '#10253f' },
  { name: 'Pike', color: '#005390' },
  { name: 'PLSQL', color: '#dad8d8' },
  { name: 'RPG', color: '#2BDE21' },
  { name: 'SuperCollider', color: '#46390b' },
  { name: 'TLA', color: '#4b0079' },
  { name: 'X10', color: '#4B6BEF' },
  { name: 'Xtend', color: '#24255d' },
  { name: 'Yacc', color: '#4B6C4B' },
  { name: 'Zephir', color: '#118f9e' },
  { name: 'Zimpl', color: '#d67711' }
];
/**
 * Get all programming languages name and their HEX color.
 * @returns {Array} Array of objects containing name and HEX color of programming languages.
 */
function getAllLanguagesColors(){
    return languageColors; 
}

/**
 * Get a name and a HEX color of programming language.
 * 
 * @returns {Object} object containing name and HEX color of programming language.
 */
function getLanguageColor(programmingLanguageName){
    const language = languageColors.find(language => language.name === programmingLanguageName);
    return language ? language : { name: "Not Found", color:"#CCCCCC" } 
}

export { getAllLanguagesColors,getLanguageColor }